version: "3.9"

services:
  smtp:
    image: docker.io/axllent/mailpit:latest
    container_name: smtp
    ports:
      - "8025:8025"    # Mailpit Web UI
      - "1025:1025"    # SMTP Port
    restart: unless-stopped
    volumes:
      - ./logs:/data
    networks:
      - smtphook

  webhook:
    build:
      context: ./webhook
    container_name: webhook
    ports:
      - "4000:4000"
    restart: unless-stopped
    networks:
      - smtphook

  webhook-server:
    build:
      context: ./webhook-server
    container_name: webhook-server
    ports:
      - "4001:4001"
    restart: unless-stopped
    networks:
      - smtphook
    depends_on:
      - webhook

  parser:
    build:
      context: ./parser
    container_name: parser
    restart: unless-stopped
    networks:
      - smtphook
    depends_on:
      - smtp
      - webhook
      - webhook-server

networks:
  smtphook:
